// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://getjlrpfsssuztcbfsbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdldGpscnBmc3NzdXp0Y2Jmc2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTQxNzAsImV4cCI6MjA2NjM5MDE3MH0._h-4Yk2Rvn2eZDGQtgS70bhJwWpZ1aG7edq2QBRhxfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);